path: "tensorflow.__internal__"
tf_module {
  member {
    name: "SymbolicTensor"
    mtype: "<class \'type\'>"
  }
  member {
    name: "types"
    mtype: "<class \'tensorflow.python.util.module_wrapper.TFModuleWrapper\'>"
  }
}
